name: Teszt workflow

on:
  push:
    branches:
      - Actions_test1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generálj egy fájlt
        run: echo "Automatikusan generált fájl" > generated_file.txt

      - name: Commit és Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automatikusan generált fájl"
          git push https://${{ secrets.GH_PAT }}@github.com/gezakeraly/Test_for_ai_assistent.git
