name: Teszt workflow

on:
  push:
    branches:
      - Actions_test1

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generálj egy fájlt
        run: echo "Automatikusan generált fájl" > generated_file.txt

      - name: Commit és Push

        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add generated_file.txt
          git commit -m "Automatikusan generált fájl [skip ci]"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/gezakeraly/Test_for_ai_assistent.git

