name: Teszt workflow

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests
        working-directory: /mnt/c/Users/szebe/OneDrive/Asztali\ gép/ÖNLAB/AI_for_ai_assistent/src

      - name: Run generate_app.py
        run: python generate_app.py
        working-directory: /mnt/c/Users/szebe/OneDrive/Asztali\ gép/ÖNLAB/AI_for_ai_assistent/src

      - name: Commit és Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add /mnt/c/Users/szebe/OneDrive/Asztali\ gép/ÖNLAB/AI_for_ai_assistent/src/todo_app.jsx
          git commit -m "Automatikusan generált React Todo alkalmazás [skip ci]"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/gezakeraly/Test_for_ai_assistent.git

