name: Teszt workflow

on:
  issues:
    types:
      - opened
      - labeled
      - edited
      - deleted

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout repo with Python script
        uses: actions/checkout@v4
        with:
          repository: 'gezakeraly/AI_for_ai_assistent'
          path: 'AI_for_ai_assistent'
          token: ${{ secrets.GH_PAT_PY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r AI_for_ai_assistent/requirements.txt

      - name: Run generate_app.py
        run: python AI_for_ai_assistent/src/generate_app.py

      - name: Commit és Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add AI_for_ai_assistent/todo_app.jsx
          git commit -m "Automatikusan generált React Todo alkalmazás [skip ci]" || echo "Nincs változás."
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/gezakeraly/Test_for_ai_assistent.git
