name: Teszt workflow

on:
  issues:
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout repo with Python script
        uses: actions/checkout@v4
        with:
          repository: 'gezakeraly/AI_for_ai_assistent'
          path: 'AI_for_ai_assistent'
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run generate_app.py
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
        run: |
          cd AI_for_ai_assistent/src  # Váltás a szkript mappájába
          python generate_app.py

      - name: Checkout repo for generated files
        uses: actions/checkout@v4
        with:
          repository: 'gezakeraly/Test_for_ai_assistent'
          path: 'Test_for_ai_assistent'
          token: ${{ secrets.GH_PAT }}

      - name: Copy generated files
        run: |
          cp -r AI_for_ai_assistent/generated_code/* Test_for_ai_assistent/generated_code/

      - name: Commit és Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cd Test_for_ai_assistent/generated_code
          git add .
          git commit -m "Automatikusan generált React Todo alkalmazás [skip ci]" || echo "Nincs változás."
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/gezakeraly/Test_for_ai_assistent.git